// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CalculateProfitMargin(arg1:service.ProfitMarginPayload):Promise<service.ProfitMarginResult>;

export function Greet(arg1:string):Promise<string>;
